import { CATEGORIES, type ToolCategoryId, type ToolDef, type ToolFaq } from "./types";

const LOCAL =
  "Processed in your browser. Files are not uploaded to Anvil servers.";

const pdfFaqs: ToolFaq[] = [
  { q: "Is the file uploaded?", a: LOCAL },
  { q: "What size can I use?", a: "Up to 25 MB per file on this device. Very large PDFs may be slow." },
];

function tool(def: ToolDef): ToolDef {
  return def;
}

export const TOOLS: ToolDef[] = [
  tool({
    id: "merge-pdf",
    slug: "merge-pdf",
    name: "Merge PDF",
    category: "pdf",
    icon: "layers",
    summary: "Combine multiple PDFs into one file.",
    description:
      "Join PDFs in the order you choose. Each document is copied page by page in your browser.",
    instructions: [
      "Add two or more PDF files.",
      "Drag to reorder if needed.",
      "Run the merge and download the combined file.",
    ],
    examples: ["Packet of signed forms", "Thesis chapters into one volume"],
    limitations: [LOCAL, "Bookmarks and some optional PDF features may be dropped."],
    faqs: pdfFaqs,
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["split-pdf", "compress-pdf", "extract-pdf-pages"],
    sort: 10,
    ui: { kind: "files", accept: "application/pdf,.pdf", multiple: true, maxFiles: 20 },
    maxBytes: 25 * 1024 * 1024,
  }),
  tool({
    id: "split-pdf",
    slug: "split-pdf",
    name: "Split PDF",
    category: "pdf",
    icon: "scissors",
    summary: "Split a PDF into single pages or a page range.",
    description: "Create one PDF per page, or extract a range such as 1-3,5 into a new document.",
    instructions: ["Add a PDF.", "Choose all pages or a range.", "Download the result or zip."],
    examples: ["1-3,8", "Each page as its own file"],
    limitations: [LOCAL, "Very large page counts create large zip files in memory."],
    faqs: pdfFaqs,
    featured: true,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["extract-pdf-pages", "merge-pdf", "rotate-pdf"],
    sort: 20,
    ui: {
      kind: "files",
      accept: "application/pdf,.pdf",
      options: [
        {
          key: "mode",
          label: "Split mode",
          type: "select",
          default: "all",
          options: [
            { value: "all", label: "Every page as its own PDF (zip)" },
            { value: "range", label: "Keep a page range as one PDF" },
          ],
        },
        { key: "range", label: "Page range", type: "text", placeholder: "1-3,5", help: "Used when mode is range." },
      ],
    },
  }),
  tool({
    id: "compress-pdf",
    slug: "compress-pdf",
    name: "Compress PDF",
    category: "pdf",
    icon: "shrink",
    summary: "Rebuild pages as compressed JPEG images.",
    description:
      "Each page is rendered and saved as a JPEG inside a new PDF. This is lossy and works best on image-heavy files.",
    instructions: ["Add a PDF.", "Choose quality.", "Compare the reported sizes before discarding the original."],
    examples: ["Scanned statements", "Photo-heavy decks"],
    limitations: [
      LOCAL,
      "Text becomes an image. Searchable text is not preserved.",
      "Simple vector PDFs may not shrink — and can grow.",
    ],
    faqs: pdfFaqs,
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["pdf-to-jpg", "compress-jpg", "merge-pdf"],
    sort: 30,
    ui: {
      kind: "files",
      accept: "application/pdf,.pdf",
      options: [
        { key: "quality", label: "JPEG quality", type: "range", min: 0.3, max: 0.9, step: 0.05, default: 0.6 },
        { key: "scale", label: "Render scale", type: "range", min: 0.7, max: 1.5, step: 0.1, default: 1.1 },
      ],
    },
  }),
  tool({
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    category: "pdf",
    icon: "file-output",
    summary: "Place JPG images on PDF pages.",
    description: "Each image becomes a page sized to the photograph.",
    instructions: ["Add one or more JPG files.", "Download the PDF."],
    examples: ["Receipts", "Scanned pages photographed on a phone"],
    limitations: [LOCAL],
    faqs: pdfFaqs,
    featured: false,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["png-to-pdf", "jpg-to-png", "compress-jpg"],
    sort: 40,
    ui: { kind: "files", accept: "image/jpeg,.jpg,.jpeg", multiple: true, maxFiles: 30 },
  }),
  tool({
    id: "png-to-pdf",
    slug: "png-to-pdf",
    name: "PNG to PDF",
    category: "pdf",
    icon: "file-output",
    summary: "Place PNG images on PDF pages.",
    description: "Each PNG becomes a page. Transparency is flattened onto white.",
    instructions: ["Add PNG files.", "Download the PDF."],
    examples: ["Screenshots", "Interface captures"],
    limitations: [LOCAL, "Alpha channels are flattened on white."],
    faqs: pdfFaqs,
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["jpg-to-pdf", "png-to-jpg", "pdf-to-png"],
    sort: 50,
    ui: { kind: "files", accept: "image/png,.png", multiple: true, maxFiles: 30 },
  }),
  tool({
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    category: "pdf",
    icon: "images",
    summary: "Render each PDF page as a JPG.",
    description: "Pages are rasterized in the browser. Output is a zip if there are several pages.",
    instructions: ["Add a PDF.", "Adjust scale if you need more detail.", "Download images."],
    examples: ["Share a page in chat", "Archive a slide as a photo"],
    limitations: [LOCAL, "Vector sharpness depends on render scale."],
    faqs: pdfFaqs,
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["pdf-to-png", "compress-pdf", "jpg-to-pdf"],
    sort: 60,
    ui: {
      kind: "files",
      accept: "application/pdf,.pdf",
      options: [{ key: "scale", label: "Render scale", type: "range", min: 1, max: 2.5, step: 0.1, default: 1.5 }],
    },
  }),
  tool({
    id: "pdf-to-png",
    slug: "pdf-to-png",
    name: "PDF to PNG",
    category: "pdf",
    icon: "images",
    summary: "Render each PDF page as a PNG.",
    description: "Lossless page images. Larger than JPG for photographs.",
    instructions: ["Add a PDF.", "Download PNG files (zipped when multiple)."],
    examples: ["UI mockups from a PDF", "Line-art pages"],
    limitations: [LOCAL],
    faqs: pdfFaqs,
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["pdf-to-jpg", "png-to-pdf", "compress-png"],
    sort: 70,
    ui: {
      kind: "files",
      accept: "application/pdf,.pdf",
      options: [{ key: "scale", label: "Render scale", type: "range", min: 1, max: 2.5, step: 0.1, default: 1.5 }],
    },
  }),
  tool({
    id: "extract-pdf-pages",
    slug: "extract-pdf-pages",
    name: "Extract PDF Pages",
    category: "pdf",
    icon: "gallery-vertical-end",
    summary: "Keep only the pages you list.",
    description: "Build a new PDF from a page list such as 1,2,5-7.",
    instructions: ["Add a PDF.", "Enter pages to keep.", "Download the new file."],
    examples: ["1,4,9-11"],
    limitations: [LOCAL],
    faqs: pdfFaqs,
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["split-pdf", "merge-pdf", "rotate-pdf"],
    sort: 80,
    ui: {
      kind: "files",
      accept: "application/pdf,.pdf",
      options: [{ key: "range", label: "Pages to keep", type: "text", placeholder: "1,2,5-7", default: "1" }],
    },
  }),
  tool({
    id: "rotate-pdf",
    slug: "rotate-pdf",
    name: "Rotate PDF",
    category: "pdf",
    icon: "rotate-cw",
    summary: "Rotate every page by 90, 180, or 270 degrees.",
    description: "Rotation is applied to page boxes in the PDF — not a re-encode.",
    instructions: ["Add a PDF.", "Choose an angle.", "Download."],
    examples: ["Landscape scans that open as portrait"],
    limitations: [LOCAL],
    faqs: pdfFaqs,
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["extract-pdf-pages", "merge-pdf", "pdf-metadata"],
    sort: 90,
    ui: {
      kind: "files",
      accept: "application/pdf,.pdf",
      options: [
        {
          key: "angle",
          label: "Angle",
          type: "select",
          default: "90",
          options: [
            { value: "90", label: "90° clockwise" },
            { value: "180", label: "180°" },
            { value: "270", label: "270° clockwise" },
          ],
        },
      ],
    },
  }),
  tool({
    id: "pdf-metadata",
    slug: "pdf-metadata",
    name: "PDF Metadata Viewer",
    category: "pdf",
    icon: "info",
    summary: "Read title, author, page count, and encryption state.",
    description: "Inspect document info without changing the file.",
    instructions: ["Add a PDF.", "Review the reported fields."],
    examples: ["Check whether a file is encrypted before sharing"],
    limitations: [LOCAL, "XMP packets are not fully parsed."],
    faqs: pdfFaqs,
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["protect-pdf", "unlock-pdf", "rotate-pdf"],
    sort: 100,
    ui: { kind: "files", accept: "application/pdf,.pdf" },
  }),
  tool({
    id: "protect-pdf",
    slug: "protect-pdf",
    name: "Protect PDF",
    category: "pdf",
    icon: "lock",
    summary: "Encrypt a PDF with a password (AES-256).",
    description: "Sets a user password so readers must unlock the file. Keep the password; Anvil does not store it.",
    instructions: ["Add a PDF.", "Enter a password.", "Download the encrypted file."],
    examples: ["A contract that should not open in a shared folder"],
    limitations: [LOCAL, "Encryption is not a substitute for access control on a server."],
    faqs: pdfFaqs,
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["unlock-pdf", "pdf-metadata", "compress-pdf"],
    sort: 110,
    ui: {
      kind: "files",
      accept: "application/pdf,.pdf",
      options: [{ key: "password", label: "Password", type: "text", placeholder: "Required" }],
    },
  }),
  tool({
    id: "unlock-pdf",
    slug: "unlock-pdf",
    name: "Unlock PDF",
    category: "pdf",
    icon: "lock-open",
    summary: "Remove encryption when you know the password.",
    description: "Opens a password-protected PDF and writes an unencrypted copy. The password is required.",
    instructions: ["Add an encrypted PDF.", "Enter the current password.", "Download the unlocked file."],
    examples: ["A file you encrypted earlier and now need to edit"],
    limitations: [LOCAL, "This cannot guess or bypass an unknown password."],
    faqs: pdfFaqs,
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["protect-pdf", "pdf-metadata", "merge-pdf"],
    sort: 120,
    ui: {
      kind: "files",
      accept: "application/pdf,.pdf",
      options: [{ key: "password", label: "Current password", type: "text", placeholder: "Required" }],
    },
  }),
  tool({
    id: "compress-jpg",
    slug: "compress-jpg",
    name: "Compress JPG",
    category: "image",
    icon: "image-down",
    summary: "Re-encode a JPEG at a chosen quality.",
    description: "Draws the image to a canvas and saves a new JPEG. Compare file sizes before replacing the original.",
    instructions: ["Add a JPG.", "Set quality.", "Download if the new size is acceptable."],
    examples: ["Email attachments", "Blog photos"],
    limitations: [LOCAL, "Repeated compression adds artifacts."],
    faqs: [{ q: "Is EXIF kept?", a: "No. Re-encoding strips metadata." }],
    featured: true,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["compress-png", "resize-image", "jpg-to-webp"],
    sort: 200,
    ui: {
      kind: "files",
      accept: "image/jpeg,.jpg,.jpeg",
      options: [{ key: "quality", label: "Quality", type: "range", min: 0.3, max: 0.95, step: 0.05, default: 0.7 }],
    },
  }),
  tool({
    id: "compress-png",
    slug: "compress-png",
    name: "Compress PNG",
    category: "image",
    icon: "image-down",
    summary: "Re-encode a PNG; optionally flatten to JPEG.",
    description:
      "PNG is lossless, so canvas re-encoding may not shrink much. Use JPEG mode when photographs can lose detail.",
    instructions: ["Add a PNG.", "Pick PNG or JPEG output.", "Check the size report."],
    examples: ["Screenshots", "Photos saved as PNG by mistake"],
    limitations: [LOCAL, "True PNG quantization is limited in the browser."],
    faqs: [{ q: "Why did size increase?", a: "Lossless PNG re-encode can grow. Try JPEG mode for photos." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["compress-jpg", "png-to-jpg", "resize-image"],
    sort: 210,
    ui: {
      kind: "files",
      accept: "image/png,.png",
      options: [
        {
          key: "mode",
          label: "Output",
          type: "select",
          default: "png",
          options: [
            { value: "png", label: "PNG (lossless)" },
            { value: "jpeg", label: "JPEG (lossy)" },
          ],
        },
        { key: "quality", label: "JPEG quality", type: "range", min: 0.4, max: 0.95, step: 0.05, default: 0.75 },
      ],
    },
  }),
  tool({
    id: "resize-image",
    slug: "resize-image",
    name: "Resize Image",
    category: "image",
    icon: "scaling",
    summary: "Scale an image to a width, height, or percent.",
    description: "Resizes JPG, PNG, or WEBP using canvas. Aspect ratio is kept unless you set both sides.",
    instructions: ["Add an image.", "Enter width, height, or percent.", "Download."],
    examples: ["1200px wide blog image", "50% thumbnail"],
    limitations: [LOCAL, "Upscaling cannot add real detail."],
    faqs: [{ q: "Which formats?", a: "JPEG, PNG, and WEBP." }],
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["crop-image", "compress-jpg", "jpg-to-webp"],
    sort: 220,
    ui: {
      kind: "files",
      accept: "image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp",
      options: [
        { key: "width", label: "Width (px)", type: "number", placeholder: "Keep", min: 1, max: 8000 },
        { key: "height", label: "Height (px)", type: "number", placeholder: "Keep", min: 1, max: 8000 },
        { key: "percent", label: "Scale percent", type: "number", placeholder: "e.g. 50", min: 1, max: 400 },
      ],
    },
  }),
  tool({
    id: "crop-image",
    slug: "crop-image",
    name: "Crop Image",
    category: "image",
    icon: "crop",
    summary: "Crop by dragging a rectangle on the preview.",
    description: "Select a region, then export JPEG or PNG.",
    instructions: ["Add an image.", "Drag on the preview to set the crop.", "Download."],
    examples: ["Square avatar from a photo"],
    limitations: [LOCAL],
    faqs: [{ q: "Can I type pixels?", a: "The selection reports pixel size; drag to adjust." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["resize-image", "compress-jpg", "png-to-jpg"],
    sort: 230,
    ui: { kind: "crop" },
  }),
  tool({
    id: "jpg-to-png",
    slug: "jpg-to-png",
    name: "JPG to PNG",
    category: "image",
    icon: "replace",
    summary: "Convert JPEG to PNG.",
    description: "Re-encodes the bitmap as PNG. Photographs usually get larger.",
    instructions: ["Add a JPG.", "Download the PNG."],
    examples: ["Need transparency later", "A pipeline that only accepts PNG"],
    limitations: [LOCAL, "JPEG artifacts remain in the pixels."],
    faqs: [{ q: "Will it look sharper?", a: "No. The pixels are the same; only the container changes." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["png-to-jpg", "jpg-to-webp", "jpg-to-pdf"],
    sort: 240,
    ui: { kind: "files", accept: "image/jpeg,.jpg,.jpeg" },
  }),
  tool({
    id: "png-to-jpg",
    slug: "png-to-jpg",
    name: "PNG to JPG",
    category: "image",
    icon: "replace",
    summary: "Convert PNG to JPEG on a white background.",
    description: "Transparency is flattened. Useful for photographs saved as PNG.",
    instructions: ["Add a PNG.", "Set quality.", "Download."],
    examples: ["Product photos"],
    limitations: [LOCAL, "Transparency is lost."],
    faqs: [{ q: "What happens to alpha?", a: "It is composited onto white." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["jpg-to-png", "compress-jpg", "png-to-pdf"],
    sort: 250,
    ui: {
      kind: "files",
      accept: "image/png,.png",
      options: [{ key: "quality", label: "Quality", type: "range", min: 0.4, max: 0.95, step: 0.05, default: 0.85 }],
    },
  }),
  tool({
    id: "jpg-to-webp",
    slug: "jpg-to-webp",
    name: "JPG to WEBP",
    category: "image",
    icon: "replace",
    summary: "Convert JPEG to WEBP.",
    description: "WEBP often shrinks photographs versus JPEG at a similar visual quality.",
    instructions: ["Add a JPG.", "Set quality.", "Download."],
    examples: ["Web delivery"],
    limitations: [LOCAL, "Older software may not open WEBP."],
    faqs: [{ q: "Is WEBP supported here?", a: "Yes, via the browser canvas encoder." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["webp-to-jpg", "compress-jpg", "png-to-jpg"],
    sort: 260,
    ui: {
      kind: "files",
      accept: "image/jpeg,.jpg,.jpeg",
      options: [{ key: "quality", label: "Quality", type: "range", min: 0.4, max: 0.95, step: 0.05, default: 0.8 }],
    },
  }),
  tool({
    id: "webp-to-jpg",
    slug: "webp-to-jpg",
    name: "WEBP to JPG",
    category: "image",
    icon: "replace",
    summary: "Convert WEBP to JPEG.",
    description: "Use when a recipient cannot open WEBP.",
    instructions: ["Add a WEBP file.", "Download JPEG."],
    examples: ["Compatibility exports"],
    limitations: [LOCAL],
    faqs: [{ q: "Animated WEBP?", a: "Only the first frame is converted." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["jpg-to-webp", "png-to-jpg", "compress-jpg"],
    sort: 270,
    ui: {
      kind: "files",
      accept: "image/webp,.webp",
      options: [{ key: "quality", label: "Quality", type: "range", min: 0.4, max: 0.95, step: 0.05, default: 0.85 }],
    },
  }),
  tool({
    id: "word-counter",
    slug: "word-counter",
    name: "Word Counter",
    category: "text",
    icon: "type",
    summary: "Count words, characters, sentences, and paragraphs.",
    description: "Counts run in the browser. Nothing is stored.",
    instructions: ["Paste or type text.", "Read the totals."],
    examples: ["Essay length", "Caption limits"],
    limitations: [LOCAL],
    faqs: [{ q: "How is a word defined?", a: "Whitespace-separated tokens after trimming." }],
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["character-counter", "case-converter", "text-cleaner"],
    sort: 300,
    ui: { kind: "text", placeholder: "Paste text to count…", rows: 12 },
  }),
  tool({
    id: "character-counter",
    slug: "character-counter",
    name: "Character Counter",
    category: "text",
    icon: "whole-word",
    summary: "Count characters with and without spaces.",
    description: "Includes UTF-16 code units as the browser sees them, plus a grapheme-aware note when possible.",
    instructions: ["Paste text.", "Read counts."],
    examples: ["Meta descriptions", "SMS drafts"],
    limitations: [LOCAL],
    faqs: [{ q: "Emoji?", a: "Counted as they appear in the string; some emoji are multiple code units." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["word-counter", "slug-generator", "text-cleaner"],
    sort: 310,
    ui: { kind: "text", placeholder: "Paste text…", rows: 12 },
  }),
  tool({
    id: "case-converter",
    slug: "case-converter",
    name: "Case Converter",
    category: "text",
    icon: "case-sensitive",
    summary: "Switch between lower, UPPER, Title, and sentence case.",
    description: "Transforms the current text without sending it anywhere.",
    instructions: ["Paste text.", "Choose a case.", "Copy the result."],
    examples: ["Headline case", "Screaming captions"],
    limitations: [LOCAL, "Title case is whitespace-based, not a linguistics engine."],
    faqs: [{ q: "Small words in titles?", a: "Every word is capitalized in Title mode." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["slug-generator", "text-cleaner", "word-counter"],
    sort: 320,
    ui: {
      kind: "text",
      placeholder: "Paste text…",
      options: [
        {
          key: "mode",
          label: "Case",
          type: "select",
          default: "lower",
          options: [
            { value: "lower", label: "lower case" },
            { value: "upper", label: "UPPER CASE" },
            { value: "title", label: "Title Case" },
            { value: "sentence", label: "Sentence case" },
            { value: "invert", label: "iNVERT cASE" },
          ],
        },
      ],
    },
  }),
  tool({
    id: "duplicate-line-remover",
    slug: "duplicate-line-remover",
    name: "Duplicate Line Remover",
    category: "text",
    icon: "list-filter",
    summary: "Drop duplicate lines, keeping first occurrence.",
    description: "Optional trim and case-insensitive compare.",
    instructions: ["Paste lines.", "Choose comparison options.", "Copy unique lines."],
    examples: ["Email lists", "Log cleanup"],
    limitations: [LOCAL],
    faqs: [{ q: "Order?", a: "First seen wins; later copies are removed." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["text-cleaner", "slug-generator", "word-counter"],
    sort: 330,
    ui: {
      kind: "text",
      placeholder: "One item per line…",
      options: [
        { key: "trim", label: "Trim lines", type: "boolean", default: true },
        { key: "insensitive", label: "Ignore case", type: "boolean", default: false },
      ],
    },
  }),
  tool({
    id: "slug-generator",
    slug: "slug-generator",
    name: "Slug Generator",
    category: "text",
    icon: "link",
    summary: "Turn a title into a URL slug.",
    description: "Lowercases, strips marks, and hyphenates words.",
    instructions: ["Enter a title.", "Copy the slug."],
    examples: ["How Anvil keeps files local → how-anvil-keeps-files-local"],
    limitations: [LOCAL],
    faqs: [{ q: "Unicode?", a: "Marks are stripped; letters are lowercased with locale-independent rules." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["case-converter", "text-cleaner", "url-encoder"],
    sort: 340,
    ui: { kind: "text", placeholder: "Page title…", rows: 4 },
  }),
  tool({
    id: "text-cleaner",
    slug: "text-cleaner",
    name: "Text Cleaner",
    category: "text",
    icon: "sparkles",
    summary: "Normalize spaces, quotes, and empty lines.",
    description: "Removes extra whitespace, optional smart-quote flattening, and blank line collapse.",
    instructions: ["Paste messy text.", "Choose options.", "Copy the cleaned result."],
    examples: ["Pasted from a PDF", "Word processor quotes"],
    limitations: [LOCAL],
    faqs: [{ q: "Does it rewrite sentences?", a: "No. It only normalizes characters and spacing." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["duplicate-line-remover", "word-counter", "case-converter"],
    sort: 350,
    ui: {
      kind: "text",
      placeholder: "Paste text to clean…",
      options: [
        { key: "spaces", label: "Collapse spaces", type: "boolean", default: true },
        { key: "blanks", label: "Collapse blank lines", type: "boolean", default: true },
        { key: "quotes", label: "Straighten quotes", type: "boolean", default: true },
      ],
    },
  }),
  tool({
    id: "json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter",
    category: "developer",
    icon: "braces",
    summary: "Pretty-print JSON with a chosen indent.",
    description: "Parses JSON in the browser and reprints it. Invalid JSON is rejected with the parser error.",
    instructions: ["Paste JSON.", "Choose indent.", "Copy formatted output."],
    examples: ["API payloads"],
    limitations: [LOCAL],
    faqs: [{ q: "Comments?", a: "Standard JSON has no comments. They will fail parsing." }],
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["json-validator", "json-minifier", "base64-encoder"],
    sort: 400,
    ui: {
      kind: "text",
      placeholder: '{ "ok": true }',
      options: [
        {
          key: "indent",
          label: "Indent",
          type: "select",
          default: "2",
          options: [
            { value: "2", label: "2 spaces" },
            { value: "4", label: "4 spaces" },
            { value: "tab", label: "Tab" },
          ],
        },
      ],
    },
  }),
  tool({
    id: "json-validator",
    slug: "json-validator",
    name: "JSON Validator",
    category: "developer",
    icon: "circle-check",
    summary: "Check whether text is valid JSON.",
    description: "Reports parse errors with the message from the engine. No schema validation.",
    instructions: ["Paste JSON.", "Read the pass or fail result."],
    examples: ["Config files"],
    limitations: [LOCAL, "This is RFC 8259 JSON, not JSON5 or JSONC."],
    faqs: [{ q: "Schema?", a: "Not included. This checks syntax only." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["json-formatter", "json-minifier", "base64-decoder"],
    sort: 410,
    ui: { kind: "text", placeholder: "Paste JSON…" },
  }),
  tool({
    id: "json-minifier",
    slug: "json-minifier",
    name: "JSON Minifier",
    category: "developer",
    icon: "minimize-2",
    summary: "Remove insignificant whitespace from JSON.",
    description: "Parse then stringify with no indent.",
    instructions: ["Paste JSON.", "Copy the minified result."],
    examples: ["Compact payloads"],
    limitations: [LOCAL],
    faqs: [{ q: "Key order?", a: "Engines may reorder keys; values are preserved." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["json-formatter", "json-validator", "text-cleaner"],
    sort: 420,
    ui: { kind: "text", placeholder: "Paste JSON…" },
  }),
  tool({
    id: "base64-encoder",
    slug: "base64-encoder",
    name: "Base64 Encoder",
    category: "developer",
    icon: "binary",
    summary: "Encode text or a file as Base64.",
    description: "Uses UTF-8 for text. Files are encoded from their bytes.",
    instructions: ["Paste text or add a file.", "Copy the Base64."],
    examples: ["Data URLs", "Small binary in JSON"],
    limitations: [LOCAL, "Huge files will strain memory."],
    faqs: [{ q: "URL-safe?", a: "Use the option to swap +/ and strip padding." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["base64-decoder", "url-encoder", "hash-generator"],
    sort: 430,
    ui: {
      kind: "files",
      accept: "*/*",
      multiple: false,
      options: [
        { key: "text", label: "Or encode this text", type: "textarea", placeholder: "Hello" },
        { key: "urlsafe", label: "URL-safe alphabet", type: "boolean", default: false },
      ],
    },
  }),
  tool({
    id: "base64-decoder",
    slug: "base64-decoder",
    name: "Base64 Decoder",
    category: "developer",
    icon: "binary",
    summary: "Decode Base64 to text or a download.",
    description: "Accepts standard or URL-safe Base64. Invalid input is rejected.",
    instructions: ["Paste Base64.", "Download bytes or copy text."],
    examples: ["Decode a data URL payload"],
    limitations: [LOCAL],
    faqs: [{ q: "Is it a file?", a: "If the bytes are not valid UTF-8 text, download them instead." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["base64-encoder", "url-decoder", "hash-generator"],
    sort: 440,
    ui: { kind: "text", placeholder: "Paste Base64…", options: [{ key: "filename", label: "Download name", type: "text", default: "decoded.bin" }] },
  }),
  tool({
    id: "url-encoder",
    slug: "url-encoder",
    name: "URL Encoder",
    category: "developer",
    icon: "app-window",
    summary: "Percent-encode text for URLs.",
    description: "encodeURIComponent for query values, or encodeURI for whole URLs.",
    instructions: ["Paste text.", "Choose component or full URL mode."],
    examples: ["Query parameter values"],
    limitations: [LOCAL],
    faqs: [{ q: "Spaces?", a: "Component mode encodes spaces as %20." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["url-decoder", "utm-builder", "slug-generator"],
    sort: 450,
    ui: {
      kind: "text",
      placeholder: "Text to encode…",
      rows: 6,
      options: [
        {
          key: "mode",
          label: "Mode",
          type: "select",
          default: "component",
          options: [
            { value: "component", label: "encodeURIComponent" },
            { value: "uri", label: "encodeURI" },
          ],
        },
      ],
    },
  }),
  tool({
    id: "url-decoder",
    slug: "url-decoder",
    name: "URL Decoder",
    category: "developer",
    icon: "app-window",
    summary: "Decode percent-encoded text.",
    description: "Invalid sequences raise an error instead of guessing.",
    instructions: ["Paste encoded text.", "Copy the decoded result."],
    examples: ["Read a query string"],
    limitations: [LOCAL],
    faqs: [{ q: "Plus signs?", a: "They are left as +. Use query parsers if you need + as space." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["url-encoder", "utm-builder", "base64-decoder"],
    sort: 460,
    ui: { kind: "text", placeholder: "https%3A%2F%2F…", rows: 6 },
  }),
  tool({
    id: "uuid-generator",
    slug: "uuid-generator",
    name: "UUID Generator",
    category: "developer",
    icon: "fingerprint",
    summary: "Generate UUID v4 identifiers.",
    description: "Uses the Web Crypto CSPRNG via crypto.randomUUID().",
    instructions: ["Choose how many to generate.", "Copy the list."],
    examples: ["Database keys", "Idempotency tokens"],
    limitations: [LOCAL, "v1/v7 are not generated here."],
    faqs: [{ q: "Are they unique?", a: "v4 IDs are random 122-bit values. Collisions are vanishingly rare." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["password-generator", "random-string", "hash-generator"],
    sort: 470,
    ui: {
      kind: "generate",
      options: [{ key: "count", label: "How many", type: "number", default: 5, min: 1, max: 100 }],
    },
  }),
  tool({
    id: "hash-generator",
    slug: "hash-generator",
    name: "Hash Generator",
    category: "developer",
    icon: "hash",
    summary: "SHA-1, SHA-256, SHA-384, SHA-512, and MD5.",
    description: "SHA family uses Web Crypto. MD5 is provided for legacy checksums only — do not use it for security.",
    instructions: ["Paste text or add a file.", "Choose algorithms.", "Copy digests."],
    examples: ["Checksum a download", "Fingerprint a payload"],
    limitations: [LOCAL, "MD5 and SHA-1 are not collision-resistant."],
    faqs: [{ q: "HMAC?", a: "Not included in this tool." }],
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["base64-encoder", "uuid-generator", "json-minifier"],
    sort: 480,
    ui: {
      kind: "files",
      accept: "*/*",
      options: [
        { key: "text", label: "Or hash this text", type: "textarea" },
        { key: "md5", label: "MD5", type: "boolean", default: true },
        { key: "sha1", label: "SHA-1", type: "boolean", default: true },
        { key: "sha256", label: "SHA-256", type: "boolean", default: true },
        { key: "sha384", label: "SHA-384", type: "boolean", default: false },
        { key: "sha512", label: "SHA-512", type: "boolean", default: false },
      ],
    },
  }),
  tool({
    id: "timestamp-converter",
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    category: "developer",
    icon: "clock",
    summary: "Unix seconds or milliseconds to a readable date, and back.",
    description: "Uses your local timezone plus UTC ISO.",
    instructions: ["Enter a timestamp or pick a date.", "Read the conversions."],
    examples: ["1700000000", "ISO dates"],
    limitations: [LOCAL],
    faqs: [{ q: "Seconds or ms?", a: "Values ≥ 1e12 are treated as milliseconds." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["age-calculator", "date-calculator", "time-calculator"],
    sort: 490,
    ui: {
      kind: "form",
      fields: [
        { key: "value", label: "Timestamp or ISO date", type: "text", placeholder: "now" },
      ],
    },
  }),
  tool({
    id: "color-converter",
    slug: "color-converter",
    name: "Color Converter",
    category: "converters",
    icon: "palette",
    summary: "Convert HEX, RGB, and HSL.",
    description: "Shows a live swatch. Invalid colors are rejected.",
    instructions: ["Enter a color in any supported notation.", "Copy the other formats."],
    examples: ["#0f6e6b", "rgb(15, 110, 107)", "hsl(178 76% 25%)"],
    limitations: [LOCAL],
    faqs: [{ q: "P3 / Lab?", a: "This tool covers sRGB HEX, RGB, and HSL." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["qr-generator", "meta-tag-generator", "unit-converter"],
    sort: 500,
    ui: { kind: "color" },
  }),
  tool({
    id: "qr-generator",
    slug: "qr-generator",
    name: "QR Code Generator",
    category: "generators",
    icon: "qr-code",
    summary: "Create a QR code PNG from text or a URL.",
    description: "Generated locally with an error-correction level you choose.",
    instructions: ["Enter the payload.", "Download the PNG."],
    examples: ["https://example.com", "Wi-Fi notes (plain text)"],
    limitations: [LOCAL, "Very long payloads produce dense codes that scan poorly."],
    faqs: [{ q: "Logo overlay?", a: "Not included — overlaying a logo can break scanning." }],
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["utm-builder", "password-generator", "url-encoder"],
    sort: 600,
    ui: {
      kind: "generate",
      options: [
        { key: "text", label: "Content", type: "textarea", placeholder: "https://" },
        {
          key: "ecc",
          label: "Error correction",
          type: "select",
          default: "M",
          options: [
            { value: "L", label: "L (7%)" },
            { value: "M", label: "M (15%)" },
            { value: "Q", label: "Q (25%)" },
            { value: "H", label: "H (30%)" },
          ],
        },
        { key: "size", label: "Size (px)", type: "number", default: 512, min: 128, max: 2048 },
      ],
    },
  }),
  tool({
    id: "password-generator",
    slug: "password-generator",
    name: "Password Generator",
    category: "generators",
    icon: "key-round",
    summary: "Generate random passwords with CSPRNG.",
    description: "Uses crypto.getRandomValues. You choose length and character classes.",
    instructions: ["Set length and classes.", "Generate.", "Copy once — Anvil does not store it."],
    examples: ["24-character mixed password"],
    limitations: [LOCAL, "If you disable too many classes, entropy drops."],
    faqs: [{ q: "Is this stored?", a: "No. Copy it to a password manager." }],
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["random-string", "uuid-generator", "hash-generator"],
    sort: 610,
    ui: {
      kind: "generate",
      options: [
        { key: "length", label: "Length", type: "number", default: 20, min: 8, max: 128 },
        { key: "lower", label: "Lowercase", type: "boolean", default: true },
        { key: "upper", label: "Uppercase", type: "boolean", default: true },
        { key: "digits", label: "Digits", type: "boolean", default: true },
        { key: "symbols", label: "Symbols", type: "boolean", default: true },
      ],
    },
  }),
  tool({
    id: "random-number",
    slug: "random-number",
    name: "Random Number Generator",
    category: "generators",
    icon: "dices",
    summary: "Uniform integers in a range using CSPRNG.",
    description: "Inclusive min and max. Not for cryptographic keys — use the password tool.",
    instructions: ["Set min, max, and count.", "Generate."],
    examples: ["1–6", "Draw 10 lottery numbers"],
    limitations: [LOCAL],
    faqs: [{ q: "Duplicates?", a: "Allowed unless you enable unique mode." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["random-string", "password-generator", "uuid-generator"],
    sort: 620,
    ui: {
      kind: "generate",
      options: [
        { key: "min", label: "Minimum", type: "number", default: 1 },
        { key: "max", label: "Maximum", type: "number", default: 100 },
        { key: "count", label: "How many", type: "number", default: 1, min: 1, max: 200 },
        { key: "unique", label: "Unique values", type: "boolean", default: false },
      ],
    },
  }),
  tool({
    id: "random-string",
    slug: "random-string",
    name: "Random String Generator",
    category: "generators",
    icon: "shuffle",
    summary: "Random alphanumeric strings.",
    description: "CSPRNG over a chosen alphabet.",
    instructions: ["Set length and alphabet.", "Generate."],
    examples: ["Coupon codes", "Test fixtures"],
    limitations: [LOCAL],
    faqs: [{ q: "Ambiguous characters?", a: "Use the no-lookalikes option to drop 0/O/1/l." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["password-generator", "uuid-generator", "random-number"],
    sort: 630,
    ui: {
      kind: "generate",
      options: [
        { key: "length", label: "Length", type: "number", default: 12, min: 1, max: 128 },
        { key: "count", label: "How many", type: "number", default: 5, min: 1, max: 50 },
        { key: "lookalikes", label: "Exclude 0/O/1/l", type: "boolean", default: true },
      ],
    },
  }),
  tool({
    id: "calculator",
    slug: "calculator",
    name: "Basic Calculator",
    category: "calculators",
    icon: "calculator",
    summary: "Add, subtract, multiply, divide, and percentages.",
    description: "Expressions are parsed — not eval’d as JavaScript.",
    instructions: ["Type an expression or use the pad.", "Read the result."],
    examples: ["12.5 * 8", "(2+3)^2"],
    limitations: [LOCAL],
    faqs: [{ q: "Order of operations?", a: "Parentheses, powers, then multiply/divide, then add/subtract." }],
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["scientific-calculator", "percentage-calculator", "unit-converter"],
    sort: 700,
    ui: { kind: "calc", variant: "basic" },
  }),
  tool({
    id: "scientific-calculator",
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    category: "calculators",
    icon: "sigma",
    summary: "Trig, logs, powers, and factorials.",
    description: "Angles are radians. Constants pi and e are available.",
    instructions: ["Enter an expression such as sin(pi/2) or log(100).", "Read the result."],
    examples: ["sqrt(2)", "sin(pi/6)", "5!"],
    limitations: [LOCAL, "Trig functions use radians."],
    faqs: [{ q: "Degrees?", a: "Convert first: sin(45 * pi / 180)." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["calculator", "percentage-calculator", "data-converter"],
    sort: 710,
    ui: { kind: "calc", variant: "scientific" },
  }),
  tool({
    id: "percentage-calculator",
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    category: "calculators",
    icon: "percent",
    summary: "Percent of, what percent, and percent change.",
    description: "Three common percentage problems on one form.",
    instructions: ["Fill the fields for the problem you need.", "Read the result."],
    examples: ["What is 18% of 240?", "12 is what percent of 80?", "80 → 100 change"],
    limitations: [LOCAL],
    faqs: [{ q: "Rounding?", a: "Results show up to 8 significant digits." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["calculator", "age-calculator", "unit-converter"],
    sort: 720,
    ui: { kind: "calc", variant: "percentage" },
  }),
  tool({
    id: "age-calculator",
    slug: "age-calculator",
    name: "Age Calculator",
    category: "calculators",
    icon: "cake",
    summary: "Exact age in years, months, and days.",
    description: "Uses calendar dates, not 365.25-day approximations.",
    instructions: ["Enter a birth date.", "Optionally set an as-of date."],
    examples: ["Age on a deadline"],
    limitations: [LOCAL],
    faqs: [{ q: "Time zones?", a: "Dates are interpreted in your local calendar." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["date-calculator", "timestamp-converter", "time-calculator"],
    sort: 730,
    ui: { kind: "calc", variant: "age" },
  }),
  tool({
    id: "date-calculator",
    slug: "date-calculator",
    name: "Date Calculator",
    category: "calculators",
    icon: "calendar",
    summary: "Add days to a date, or difference between two dates.",
    description: "Inclusive options are stated in the result.",
    instructions: ["Choose add or difference.", "Enter dates."],
    examples: ["Invoice + 30 days", "Days between two milestones"],
    limitations: [LOCAL],
    faqs: [{ q: "Business days?", a: "This counts calendar days only." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["age-calculator", "time-calculator", "timestamp-converter"],
    sort: 740,
    ui: { kind: "calc", variant: "date" },
  }),
  tool({
    id: "time-calculator",
    slug: "time-calculator",
    name: "Time Calculator",
    category: "calculators",
    icon: "timer",
    summary: "Add durations or subtract two clock times.",
    description: "Durations use hours, minutes, and seconds.",
    instructions: ["Enter times or durations.", "Read the total."],
    examples: ["2h 15m + 40m", "09:00 to 17:30"],
    limitations: [LOCAL],
    faqs: [{ q: "Overnight?", a: "If the end is earlier than the start, 24 hours are added." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["date-calculator", "download-time", "timestamp-converter"],
    sort: 750,
    ui: { kind: "calc", variant: "time" },
  }),
  tool({
    id: "unit-converter",
    slug: "unit-converter",
    name: "Unit Converter",
    category: "converters",
    icon: "ruler",
    summary: "Length, mass, temperature, volume, area, and speed.",
    description: "Conversions use fixed SI factors. Temperature uses the proper formulas.",
    instructions: ["Choose a category.", "Enter a value and units."],
    examples: ["10 mi → km", "32 °F → °C"],
    limitations: [LOCAL, "Survey feet and other specialized units are omitted."],
    faqs: [{ q: "UK vs US gallon?", a: "Volume uses litres, millilitres, US gallons, and Imperial gallons." }],
    featured: true,
    homepage: true,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["data-converter", "calculator", "percentage-calculator"],
    sort: 760,
    ui: { kind: "calc", variant: "unit" },
  }),
  tool({
    id: "data-converter",
    slug: "data-converter",
    name: "Data Converter",
    category: "converters",
    icon: "hard-drive",
    summary: "Convert bits and bytes (SI and IEC).",
    description: "SI uses 1000. IEC uses 1024 (KiB, MiB, GiB).",
    instructions: ["Enter a size.", "Pick from and to units."],
    examples: ["1 GiB in MB", "8 Mb/s in MB/s is a different tool — this converts stored size."],
    limitations: [LOCAL],
    faqs: [{ q: "KB or KiB?", a: "KB is 1000 bytes. KiB is 1024 bytes." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["download-time", "unit-converter", "compress-pdf"],
    sort: 770,
    ui: { kind: "calc", variant: "data" },
  }),
  tool({
    id: "download-time",
    slug: "download-time",
    name: "Download Time Calculator",
    category: "calculators",
    icon: "download",
    summary: "Estimate time from file size and bandwidth.",
    description: "Uses bits per second for the link. Overhead is ignored unless you add a margin.",
    instructions: ["Enter file size and speed.", "Read hours, minutes, seconds."],
    examples: ["4 GB on 40 Mbps"],
    limitations: [LOCAL, "Real transfers are slower than line rate."],
    faqs: [{ q: "MB vs Mb?", a: "File size uses bytes. Speed uses bits per second unless you pick byte units." }],
    featured: false,
    homepage: false,
    seo: false,
    cost: 1,
    engine: "browser",
    related: ["data-converter", "time-calculator", "unit-converter"],
    sort: 780,
    ui: { kind: "calc", variant: "download" },
  }),
  tool({
    id: "meta-tag-generator",
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    category: "seo",
    icon: "code-xml",
    summary: "Build title, description, and Open Graph tags.",
    description: "Produces HTML you can paste into a document head. It does not fetch your site.",
    instructions: ["Fill in the fields.", "Copy the snippet."],
    examples: ["A landing page head"],
    limitations: [LOCAL, "This does not audit an existing page."],
    faqs: [{ q: "Twitter tags?", a: "summary_large_image tags are included when you provide an image URL." }],
    featured: false,
    homepage: true,
    seo: true,
    cost: 1,
    engine: "browser",
    related: ["robots-txt-generator", "sitemap-generator", "utm-builder"],
    sort: 800,
    ui: {
      kind: "form",
      fields: [
        { key: "title", label: "Title", type: "text", placeholder: "Page title" },
        { key: "description", label: "Description", type: "textarea", placeholder: "Up to ~160 characters" },
        { key: "canonical", label: "Canonical URL", type: "text", placeholder: "https://" },
        { key: "image", label: "Share image URL", type: "text" },
        { key: "site", label: "Site name", type: "text", default: "Anvil" },
      ],
    },
  }),
  tool({
    id: "robots-txt-generator",
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    category: "seo",
    icon: "bot",
    summary: "Compose a robots.txt file.",
    description: "Does not fetch your host. You are responsible for not blocking resources you need crawled.",
    instructions: ["Set allow/disallow paths.", "Add a sitemap URL.", "Copy the file."],
    examples: ["Allow all plus a sitemap"],
    limitations: [LOCAL, "Never Disallow: / unless you intend to hide the site from crawlers."],
    faqs: [{ q: "AI crawlers?", a: "Add extra user-agents only if you understand the effect." }],
    featured: false,
    homepage: false,
    seo: true,
    cost: 1,
    engine: "browser",
    related: ["sitemap-generator", "meta-tag-generator", "utm-builder"],
    sort: 810,
    ui: {
      kind: "form",
      fields: [
        {
          key: "mode",
          label: "Default",
          type: "select",
          default: "allow",
          options: [
            { value: "allow", label: "Allow all" },
            { value: "disallow", label: "Disallow all" },
          ],
        },
        { key: "disallow", label: "Extra disallow paths (one per line)", type: "textarea", placeholder: "/admin" },
        { key: "sitemap", label: "Sitemap URL", type: "text", placeholder: "https://example.com/sitemap.xml" },
      ],
    },
  }),
  tool({
    id: "sitemap-generator",
    slug: "sitemap-generator",
    name: "Sitemap Generator",
    category: "seo",
    icon: "map",
    summary: "Build an XML sitemap from a URL list.",
    description: "One URL per line. Invalid URLs are skipped and listed.",
    instructions: ["Paste absolute URLs.", "Download sitemap.xml."],
    examples: ["A small brochure site"],
    limitations: [LOCAL, "This does not crawl. You supply the URLs."],
    faqs: [{ q: "Index files?", a: "For fewer than 50,000 URLs a single sitemap is enough." }],
    featured: false,
    homepage: false,
    seo: true,
    cost: 1,
    engine: "browser",
    related: ["robots-txt-generator", "meta-tag-generator", "slug-generator"],
    sort: 820,
    ui: {
      kind: "text",
      placeholder: "https://example.com/\nhttps://example.com/about",
      rows: 12,
    },
  }),
  tool({
    id: "utm-builder",
    slug: "utm-builder",
    name: "UTM Builder",
    category: "seo",
    icon: "megaphone",
    summary: "Add campaign parameters to a URL.",
    description: "Encodes utm_source, utm_medium, utm_campaign, utm_term, and utm_content.",
    instructions: ["Enter a base URL and campaign fields.", "Copy the result."],
    examples: ["Newsletter links"],
    limitations: [LOCAL],
    faqs: [{ q: "Existing query?", a: "UTM params are merged onto the current query string." }],
    featured: false,
    homepage: false,
    seo: true,
    cost: 1,
    engine: "browser",
    related: ["url-encoder", "meta-tag-generator", "qr-generator"],
    sort: 830,
    ui: {
      kind: "form",
      fields: [
        { key: "url", label: "Base URL", type: "text", placeholder: "https://example.com/page" },
        { key: "source", label: "utm_source", type: "text", placeholder: "newsletter" },
        { key: "medium", label: "utm_medium", type: "text", placeholder: "email" },
        { key: "campaign", label: "utm_campaign", type: "text", placeholder: "spring" },
        { key: "term", label: "utm_term", type: "text" },
        { key: "content", label: "utm_content", type: "text" },
      ],
    },
  }),
];

const bySlug = new Map(TOOLS.map((t) => [t.slug, t]));

export function getTool(slug: string): ToolDef | undefined {
  return bySlug.get(slug);
}

export function toolsForCategory(id: ToolCategoryId, seoEnabled: boolean): ToolDef[] {
  return TOOLS.filter((t) => t.category === id && (seoEnabled || !t.seo)).sort((a, b) => a.sort - b.sort);
}

export function visibleTools(seoEnabled: boolean): ToolDef[] {
  return TOOLS.filter((t) => seoEnabled || !t.seo);
}

export function categoryMeta(id: ToolCategoryId) {
  return CATEGORIES.find((c) => c.id === id)!;
}

export function searchTools(q: string, seoEnabled: boolean): ToolDef[] {
  const s = q.trim().toLowerCase();
  if (!s) return visibleTools(seoEnabled);
  return visibleTools(seoEnabled).filter((t) => {
    const hay = `${t.name} ${t.summary} ${t.description} ${t.category} ${t.slug}`.toLowerCase();
    return hay.includes(s);
  });
}
